src/Entity/Vinyl.php
<?php

namespace App\Entity;

use App\Repository\VinylRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VinylRepository::class)
 */
class Vinyl
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $release_date;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="vinyls")
     */
    private $artist;

    /**
     * @ORM\ManyToOne(targetEntity=Album::class, inversedBy="vinyl")
     */
    private $album;

    /**
     * @ORM\OneToMany(targetEntity=Track::class, mappedBy="vinyl", cascade = {"remove"})
     */
    private $tracks;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, mappedBy="vinyl")
     */
    private $genres;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="vinyls")
     */
    private $users;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pressing_number;

    public function __construct()
    {
        $this->tracks = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }

    /**
     * @return Collection|Track[]
     */
    public function getTracks(): Collection
    {
        return $this->tracks;
    }

    public function addTrack(Track $track): self
    {
        if (!$this->tracks->contains($track)) {
            $this->tracks[] = $track;
            $track->setVinyl($this);
        }

        return $this;
    }

    public function removeTrack(Track $track): self
    {
        if ($this->tracks->removeElement($track)) {
            // set the owning side to null (unless already changed)
            if ($track->getVinyl() === $this) {
                $track->setVinyl(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
            $genre->addVinyl($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeVinyl($this);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addVinyl($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeVinyl($this);
        }

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPressingNumber(): ?string
    {
        return $this->pressing_number;
    }

    public function setPressingNumber(string $pressing_number): self
    {
        $this->pressing_number = $pressing_number;

        return $this;
    }
}

src/Controller/DetailsController.php
<?php

namespace App\Controller;

use App\Repository\AlbumRepository;
use App\Repository\ArtistRepository;
use App\Repository\GenreRepository;
use App\Repository\TrackRepository;
use App\Repository\VinylRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DetailsController extends AbstractController
{
    /**
     * Permet d'afficher la page d'un vinyle
     *
     * @Route("/vinyle/{id}", name="vinyl")
     *
     * @param VinylRepository $repo
     * @param $id
     *
     * @return Response
     */
    public function vinylDetail(VinylRepository $repo, $id): Response
    {
        $user = false;
        $userVinyls = null;

        $vinyl = $repo->find($id);

        if ($this->getUser()){
            $userVinyls = $this->getUser()->getVinyls();
        }

        return $this->render('details/vinyl.html.twig', [
            'vinyl' => $vinyl,
            'userVinyls' => $userVinyls
        ]);
    }

    /**
     * Permet d'afficher la page d'une chanson
     *
     * @Route("/track/{id}", name="track")
     *
     * @param TrackRepository $repo
     * @param $id
     *
     * @return Response
     */
    public function trackDetail(TrackRepository $repo, $id): Response
    {
        $track = $repo->find($id);
        return $this->render('details/track.html.twig', [
            'track' => $track
        ]);
    }

    /**
     * Permet d'afficher la page d'un album
     *
     * @Route("/album/{id}", name="album")
     *
     * @param AlbumRepository $repo
     * @param $id
     *
     * @return Response
     */
    public function albumDetail(AlbumRepository $repo, $id): Response
    {
        $album = $repo->find($id);
        return $this->render('details/album.html.twig', [
            'album' => $album
        ]);
    }

    /**
     * Permet d'afficher la page d'un artiste
     *
     * @Route("/artist/{id}", name="artist")
     *
     * @param ArtistRepository $repo
     * @param $id
     *
     * @return Response
     */
    public function artistDetail(ArtistRepository $repo, $id): Response
    {
        $artist = $repo->find($id);
        return $this->render('details/artist.html.twig', [
            'artist' => $artist
        ]);
    }

    /**
     * Permet d'afficher la page d'un genre
     *
     * @Route("/genre/{id}", name="genre")
     *
     * @param GenreRepository $repo
     * @param $id
     * @param PaginatorInterface $paginator
     * @param Request $request
     *
     * @return Response
     */
    public function genreDetail(GenreRepository $repo, $id, PaginatorInterface $paginator, Request $request): Response
    {
        $genre = $repo->find($id);

        $artists = $genre->getArtists();

        $artists = $paginator->paginate(
            $artists,
            $request->query->getInt('page', 1),
            4
        );

        return $this->render('details/genre.html.twig', [
            'genre'     => $genre,
            'artists'   => $artists
        ]);
    }
}

templates/details/album.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ album.artist.name }} - {{ album.name }}{% endblock %}

{% block body %}
    <h1>{{ album.name }}</h1>

    <h2><a href="{{ path('artist', {id: album.artist.id}) }}">{{ album.artist.name }}</a></h2>

    <h2 class="h5">Genre :
        {% for genre in album.genres %}
            <a href="{{ path('genre',{id:genre.id}) }}">{{ genre.name }}</a>
            {% if loop.last != true %} / {% endif %}
        {% endfor %}
    </h2>

    <p class="col-8">{{ album.description }}</p>

    <img src="{{ album.photo }}" alt="" class="mh-23">

    {% if admin %}
        <div>
            <a href="{{ path('updateAlbum',{id:album.id}) }}" class="btn btn-primary my-2">
                Mettre à jour {{ album.name }}
            </a>
        </div>
    {% endif %}

    <ul class="list-group col-6 mb-3">
        <h2>Tracklist :</h2>
        {% if admin %}
            <div>
                <a href="{{ path('addTrackByAlbum', {id:album.id}) }}" class="btn btn-primary my-2">
                    Ajouter une chanson
                </a>
            </div>
        {% endif %}
        {% for track in album.tracks | sort((a, b) => a.position <=> b.position) %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <div>{{ track.title }} ({{ track.duration }} sec)</div>
                    <div>position : {{ track.position }}
                        {% if admin %}
                            <a href="{{ path('updateTrack', {id:track.id}) }}" class="btn btn-primary fs-6">
                                <i class="fas fa-pen"></i>
                            </a>

                            <!-- Button trigger modal -->
                            <button type="button"
                                    class="fw-bold btn btn-danger"
                                    data-bs-toggle="modal"
                                    data-bs-target="#removeTrackFromVinyl">
                                X
                            </button>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="removeTrackFromVinyl"
                                 tabindex="-1"
                                 aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Attention</h5>
                                            <button type="button"
                                                    class="btn-close"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close">
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p class="h5">
                                                Souhaitez vous réellement supprimer {{ track.title }}
                                                de {{ track.album.artist.name}} définitivement ?
                                            </p>
                                            <a href="{{ path('deleteTrack', {id:track.id}) }}"
                                               class="fw-bold btn btn-danger">
                                                Oui
                                            </a>
                                            <button type="button"
                                                    class="btn btn-primary"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close">
                                                Non
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>


    <h2>Vinyles issus de cet album :</h2>
    {% if admin %}
        <div>
            <a href="{{ path('addVinylByAlbum', {id:album.id}) }}" class="btn btn-primary my-2">Ajouter un vinyl</a>
        </div>
    {% endif %}
    {% if album.vinyl|length > 0 %}
        <ul class="list-group col-6 mb-2">
        {% for vinyl in album.vinyl %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a class="text-dark primary-hover text-decoration-none" href="{{ path('vinyl', {id: vinyl.id}) }}">
                    {{ vinyl.title }} ({{ vinyl.releasedate | date("d/m/Y") }})
                </a>
                <div class="col-3 d-flex align-items-center justify-content-between">
                    {% if app.user %}
                        {% if vinyl not in app.user.vinyls %}
                            <a href="{{ path('addVinylToUserCollection', {id:vinyl.id, userId: app.user.id}) }}"
                               data-bs-toggle="tooltip"
                               data-bs-placement="top"
                               title="Ajouter à ma collection"
                               class="text-decoration-none">
                                <i class="far fa-plus-square fs-2">

                                </i>
                            </a>
                        {% else %}
                            <i class="far fa-check-circle fs-2 primary-color"
                               data-bs-toggle="tooltip"
                               data-bs-placement="top"
                               title="Vous possédez ce vinyle"></i>
                            <p class="m-0"></p>
                        {% endif %}
                    {% endif %}
                    {% if admin %}
                        <a href="{{ path('update_vinyl', {id:vinyl.id}) }}" class="btn btn-primary text-end">
                            <i class="fas fa-pen"></i>
                        </a>

                        <!-- Button trigger modal -->
                        <button type="button"
                                class="fw-bold btn btn-danger text-end"
                                data-bs-toggle="modal"
                                data-bs-target="#removeVinylFromCollection">
                            X
                        </button>

                        <!-- Modal -->
                        <div class="modal fade"
                             id="removeVinylFromCollection"
                             tabindex="-1"
                             aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Attention</h5>
                                        <button type="button"
                                                class="btn-close"
                                                data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p class="h5">
                                            Souhaitez vous réellement supprimer {{ vinyl.title }}
                                            ({{ vinyl.pressingNumber }}) définitivement ?
                                        </p>
                                        <a href="{{ path('deleteVinyl', {id:vinyl.id}) }}"
                                           class="fw-bold btn btn-danger text-end">
                                            Oui
                                        </a>
                                        <button type="button"
                                                class="btn btn-primary"
                                                data-bs-dismiss="modal"
                                                aria-label="Close">
                                            Non
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Cet album n'a pas encore de vinyl, nous allons vite lui en ajouter !</p>
    {% endif %}
{% endblock %}

templates/details/artist.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ artist.name }}{% endblock %}

{% block body %}
    <h1>{{ artist.name | capitalize}}</h1>
    {% if admin %}
        <div class="my-2">
            <a href="{{ path('updateArtist', {id:artist.id}) }}" class="btn btn-info">
                Mettre à jour {{ artist.name }}
            </a>
        </div>
    {% endif %}
    {% if artist.photo | length > 0 %}
        <img src="{{ asset('images/uploads/artist_photos/' ~ artist.photo) }}" alt="" class="mh-23">
    {% else %}
        <img src="{{ asset('images/avatar.png') }}" alt="Avatar" class="mh-23">
    {% endif %}
    <h2>Genres</h2>
    <ul class="list-group">
        {% for genre in artist.genres %}
            <li class="list-group-item w-50"><a href="{{ path('genre', {id:genre.id}) }}">{{ genre.name }}</a></li>
        {% endfor %}
    </ul>

    <h2>Description</h2>
    <p class="bg-white p-1 col-8">{{ artist.description }}</p>

    <h2>Albums :</h2>
    {% if admin %}
        <div>
            <a href="{{ path('addAlbumByArtist', {id:artist.id}) }}" class="btn btn-info mb-3">Ajouter un album</a>
        </div>
    {% endif %}
    {% if artist.albums | length > 0 %}
        <ul class="list-group mb-3">
            {% set i = 1 %}
            {% for album in artist.albums %}
                <li class="list-group-item w-50 d-flex justify-content-between align-items-center">
                    <a href="{{ path('album', {id: album.id}) }}" class="text-decoration-none">
                        <img src="{{ album.photo }}" alt="{{ album.name }}" class="mx-h-3">
                        {{ album.name }}
                    </a>
                    {% if admin %}
                        <div>
                            <a href="{{ path('updateAlbum', {id:album.id}) }}" class="btn btn-primary text-end me-1">
                                <i class="fas fa-pen"></i>
                            </a>

                            <!-- Button trigger modal -->
                            <button type="button"
                                    class="fw-bold btn btn-danger text-end"
                                    data-bs-toggle="modal"
                                    data-bs-target="#removeAlbum{{ i }}">
                                X
                            </button>

                            <!-- Modal 1 -->
                            <div class="modal fade"
                                 id="removeAlbum{{ i }}"
                                 tabindex="-1"
                                 aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Attention</h5>
                                            <button type="button"
                                                    class="btn-close"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <p class="h5">
                                                Souhaitez vous réellement supprimer {{ artist.name }} définitivement ?
                                                Cette action efface également tous les titres de cet album
                                                ainsi que tous ses vinyles !!
                                            </p>
                                            <button type="button"
                                                    class="fw-bold btn btn-danger text-end"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#removeArtist{{ i+1 }}">
                                                Supprimer
                                            </button>
                                            <button type="button"
                                                    class="btn btn-primary"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close"
                                            >
                                                Non
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Modal 2 -->
                            <div class="modal fade"
                                 id="removeArtist{{ i+1 }}"
                                 tabindex="-1"
                                 aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">
                                                Attention
                                            </h5>
                                            <button type="button"
                                                    class="btn-close"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close">
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p class="h5">Vous êtes sûr ? Cette action est irreversible !</p>
                                            <a href="{{ path('deleteAlbum', {id:album.id}) }}"
                                               class="fw-bold btn btn-danger text-end">
                                                Oui, je suis sûr.
                                            </a>
                                            <button type="button"
                                                    class="btn btn-primary"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close">
                                                Non
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% set i = i + 2 %}
                    {% endif %}
                </li>
                {% set i = i + 2 %}
            {% endfor %}
        </ul>
    {% else %}
        <p>Cet artiste n'a pas encore d'album renseigné. Nous allons en ajouter sous peu !</p>
    {% endif %}
{% endblock %}

templates/details/genre.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ genre.name }}{% endblock %}

{% block body %}
    <h1>{{ genre.name }}</h1>

    {% if genre.image %}
        <img src="{{ genre.image }}" alt="{{ genre.name }}" class="mh-12 my-2">
    {% endif %}

    <p class="my-2 col-8">{{ genre.description }}</p>

    {% if admin %}
        <div class="my-2">
            <a href="{{ path('updateGenre', {id:genre.id}) }}" class="btn btn-info my-2">
                Mettre à jour {{ genre.name }}
            </a>
        </div>
    {% endif %}

    <h2>Artistes :</h2>
    {% if genre.artists | length > 0 %}
        <div class="row">
            {% for artist in artists %}
                <div class="col-6 card-group">
                    <div class="card shadow my-3">
                        <a href="{{ path('artist', {id:artist.id}) }}">
                            <img src="{{ asset('images/uploads/artist_photos/' ~ artist.photo) }}" alt="{{ artist.name }}" class="he-25 w-100 object-fit-cover">
                        </a>
                        <div class="card-body">
                            <h2>
                                <a href="{{ path('artist', {id: artist.id}) }}"
                                   class="text-dark primary-hover text-decoration-none">
                                    {{ artist.name }}
                                </a>
                            </h2>
                            {% if artist.genres | length > 1 %}
                                <p>Autres genres :
                                    {% for artist_genre in artist.genres %}
                                        {% if artist_genre.id != genre.id  %}
                                            <a href="{{ path('genre', {id:artist_genre.id}) }}">{{ artist_genre.name }}</a>{% if artist.genres | length > 2 and loop.last != true %}, {% endif%}
                                        {% endif %}
                                    {% endfor %}
                                </p>
                            {% endif%}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="pagination my-2">
                {{ knp_pagination_render(artists) }}
            </div>
        </div>

    {% else %}
        <p>Ce genre n'a pas d'artiste.</p>
        {% if admin %}
            <div class="col-2 my-2">
                <a href="{{ path("add_artist") }}"
                   class="btn btn-primary">
                    Ajouter un artiste
                </a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/details/track.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ track.album.artist.name }} - {{ track.album.name }}{% endblock %}

{% block body %}
    <h1>{{ track.title }}</h1>

    <h2><a href="{{ path('artist',{id:track.album.artist.id}) }}">{{ track.album.artist.name }}</a></h2>
    <h2><a href="{{ path('album',{id:track.album.id}) }}">{{ track.album.name }}</a></h2>

    <p>{{ track.duration }} {% if track.duration >= 1 %}minutes{% else %}secondes{% endif %}</p>
{% endblock %}

templates/details/vinyl.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ vinyl.artist.name }} - {{ vinyl.title }}{% endblock %}

{% block body %}
    <h1>{{ vinyl.title }} - {{ vinyl.pressingNumber }}</h1>

    <h2 class="h5">Genre : {% for genre in vinyl.genres %}<a
            href="{{ path('genre',{id:genre.id}) }}">{{ genre.name }}</a> {% if loop.last != true %} / {% endif %}{% endfor %}
    </h2>

    <h2><a href="{{ path('artist', {id: vinyl.artist.id}) }}">{{ vinyl.artist.name }}</a></h2>
    <h3 class="h4">Date de sortie : {{ vinyl.releaseDate | date("d/m/Y") }}</h3>
    <h3 class="h5">Album : <a href="{{ path('album', {id:vinyl.album.id}) }}">{{ vinyl.album.name }}</a></h3>

    {% if vinyl.price > 0 %}
        <p>Prix : {{ vinyl.price }} euros</p>
    {% endif %}
    {% if admin %}
        <div class="mb-3">
            <a href="{{ path('update_vinyl', {id:vinyl.id}) }}" class="btn btn-primary">
                Mettre à jour ce vinyl
            </a>
        </div>
    {% endif %}

    <img src="{{ vinyl.photo }}" alt="" class="mh-23">

    {% if app.user %}
        {% if vinyl not in app.user.vinyls %}
            <div>
                <a href="{{ path('addVinylToUserCollection', {id:vinyl.id, userId: app.user.id}) }}"
                   class="btn btn-primary my-2">Ajouter ce vinyle à ma collection</a>
            </div>
        {% else %}
            <p>Vous possédez ce vinyle</p>
        {% endif %}
    {% endif %}

    <h2>Tracklist :</h2>
    <ul class="list-group col-6">
        {% if vinyl.album.tracks | length > 0 %}
            {% for track in vinyl.album.tracks %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ track.title }} ({{ track.duration }} sec)</span>
                    <span>position : {{ track.position }}</span></li>
            {% endfor %}
        {% else %}
            <li class="list-group-item d-flex justify-content-between align-items-center col-6">L'album dont est issu ce
                vinyl n'a pas de chansons
            </li>
        {% endif %}
    </ul>
{% endblock %}